baseURL = "https://www.seoulhunter.cc/"
languageCode = "ko-kr"
title = "City Hunter. Seoul"
theme = "origin"


publishDir = "docs"

tags = ["blog", "responsive", "light", "simple"]
[params]
  featured = false